---
- name: Update Helm repositories
  command: helm repo update

- name: Add nginx-edge chart repo
  command: helm repo add nginx-edge "https://helm.nginx.com/edge"

- name: Create crds
  command: "kubectl apply -f crds/"

- name: Deploy latest version of nginx-edge chart inside monitoring namespace with values      
  command: helm upgrade --install app-nginx nginx-edge/nginx-ingress controller.hostNetwork=true,controller.kind=DaemonSet

# - name: create namespace for cert-manager
#   command: helm upgrade --install namespace cert-manager

- name: add repo for cert-manager
  command: helm repo add jetstack https://charts.jetstack.io

- name: apply crds
  command: kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.crds.yaml

- name: configure cluster to use Let`s encrypt cert for ingress-controller
  command: kubectl apply -f install-nginx-ingress-controller-role/tasks/letsencrypt-prod.yaml 

- name: install cert-manager
  command: helm upgrade --install cert-manager jetstack/cert-manager --namespace=cert-manager --version v1.0.4 --set ingressShim.defaultIssuerName=letsencrypt-prod --set ingressShim.defaultIssuerKind=ClusterIssuer

- name: install ingress
  command: kubectl apply -f ingress/ingress.yaml

- name: install metric server
  command: kubectl apply -f metric-server/components-modified.yaml

# helm upgrade --install app-nginx nginx-ingress
# helm upgrade --install cert-manager cert-manager --namespace=cert-manager --version v1.0.3 